/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ArrestCalculatorRouteImport } from './routes/arrest-calculator'
import { Route as ArrestReportRouteImport } from './routes/arrest-report'
import { Route as CaselawRouteImport } from './routes/caselaw'
import { Route as FieldInterviewKartiRouteImport } from './routes/field-interview-karti'
import { Route as IfadeRaporuRouteImport } from './routes/ifade-raporu'
import { Route as OlayRaporuRouteImport } from './routes/olay-raporu'
import { Route as PaperworkGeneratorsRouteImport } from './routes/paperwork-generators'
import { Route as PenalCodeRouteImport } from './routes/penal-code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArrestCalculatorRoute = ArrestCalculatorRouteImport.update({
  id: '/arrest-calculator',
  path: '/arrest-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const ArrestReportRoute = ArrestReportRouteImport.update({
  id: '/arrest-report',
  path: '/arrest-report',
  getParentRoute: () => rootRouteImport,
} as any)
const CaselawRoute = CaselawRouteImport.update({
  id: '/caselaw',
  path: '/caselaw',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldInterviewKartiRoute = FieldInterviewKartiRouteImport.update({
  id: '/field-interview-karti',
  path: '/field-interview-karti',
  getParentRoute: () => rootRouteImport,
} as any)
const IfadeRaporuRoute = IfadeRaporuRouteImport.update({
  id: '/ifade-raporu',
  path: '/ifade-raporu',
  getParentRoute: () => rootRouteImport,
} as any)
const OlayRaporuRoute = OlayRaporuRouteImport.update({
  id: '/olay-raporu',
  path: '/olay-raporu',
  getParentRoute: () => rootRouteImport,
} as any)
const PaperworkGeneratorsRoute = PaperworkGeneratorsRouteImport.update({
  id: '/paperwork-generators',
  path: '/paperwork-generators',
  getParentRoute: () => rootRouteImport,
} as any)
const PenalCodeRoute = PenalCodeRouteImport.update({
  id: '/penal-code',
  path: '/penal-code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arrest-calculator': typeof ArrestCalculatorRoute
  '/arrest-report': typeof ArrestReportRoute
  '/caselaw': typeof CaselawRoute
  '/field-interview-karti': typeof FieldInterviewKartiRoute
  '/ifade-raporu': typeof IfadeRaporuRoute
  '/olay-raporu': typeof OlayRaporuRoute
  '/paperwork-generators': typeof PaperworkGeneratorsRoute
  '/penal-code': typeof PenalCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arrest-calculator': typeof ArrestCalculatorRoute
  '/arrest-report': typeof ArrestReportRoute
  '/caselaw': typeof CaselawRoute
  '/field-interview-karti': typeof FieldInterviewKartiRoute
  '/ifade-raporu': typeof IfadeRaporuRoute
  '/olay-raporu': typeof OlayRaporuRoute
  '/paperwork-generators': typeof PaperworkGeneratorsRoute
  '/penal-code': typeof PenalCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arrest-calculator': typeof ArrestCalculatorRoute
  '/arrest-report': typeof ArrestReportRoute
  '/caselaw': typeof CaselawRoute
  '/field-interview-karti': typeof FieldInterviewKartiRoute
  '/ifade-raporu': typeof IfadeRaporuRoute
  '/olay-raporu': typeof OlayRaporuRoute
  '/paperwork-generators': typeof PaperworkGeneratorsRoute
  '/penal-code': typeof PenalCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/arrest-calculator'
    | '/arrest-report'
    | '/caselaw'
    | '/field-interview-karti'
    | '/ifade-raporu'
    | '/olay-raporu'
    | '/paperwork-generators'
    | '/penal-code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/arrest-calculator'
    | '/arrest-report'
    | '/caselaw'
    | '/field-interview-karti'
    | '/ifade-raporu'
    | '/olay-raporu'
    | '/paperwork-generators'
    | '/penal-code'
  id:
    | '__root__'
    | '/'
    | '/arrest-calculator'
    | '/arrest-report'
    | '/caselaw'
    | '/field-interview-karti'
    | '/ifade-raporu'
    | '/olay-raporu'
    | '/paperwork-generators'
    | '/penal-code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArrestCalculatorRoute: typeof ArrestCalculatorRoute
  ArrestReportRoute: typeof ArrestReportRoute
  CaselawRoute: typeof CaselawRoute
  FieldInterviewKartiRoute: typeof FieldInterviewKartiRoute
  IfadeRaporuRoute: typeof IfadeRaporuRoute
  OlayRaporuRoute: typeof OlayRaporuRoute
  PaperworkGeneratorsRoute: typeof PaperworkGeneratorsRoute
  PenalCodeRoute: typeof PenalCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arrest-calculator': {
      id: '/arrest-calculator'
      path: '/arrest-calculator'
      fullPath: '/arrest-calculator'
      preLoaderRoute: typeof ArrestCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arrest-report': {
      id: '/arrest-report'
      path: '/arrest-report'
      fullPath: '/arrest-report'
      preLoaderRoute: typeof ArrestReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caselaw': {
      id: '/caselaw'
      path: '/caselaw'
      fullPath: '/caselaw'
      preLoaderRoute: typeof CaselawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-interview-karti': {
      id: '/field-interview-karti'
      path: '/field-interview-karti'
      fullPath: '/field-interview-karti'
      preLoaderRoute: typeof FieldInterviewKartiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ifade-raporu': {
      id: '/ifade-raporu'
      path: '/ifade-raporu'
      fullPath: '/ifade-raporu'
      preLoaderRoute: typeof IfadeRaporuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/olay-raporu': {
      id: '/olay-raporu'
      path: '/olay-raporu'
      fullPath: '/olay-raporu'
      preLoaderRoute: typeof OlayRaporuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paperwork-generators': {
      id: '/paperwork-generators'
      path: '/paperwork-generators'
      fullPath: '/paperwork-generators'
      preLoaderRoute: typeof PaperworkGeneratorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/penal-code': {
      id: '/penal-code'
      path: '/penal-code'
      fullPath: '/penal-code'
      preLoaderRoute: typeof PenalCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArrestCalculatorRoute: ArrestCalculatorRoute,
  ArrestReportRoute: ArrestReportRoute,
  CaselawRoute: CaselawRoute,
  FieldInterviewKartiRoute: FieldInterviewKartiRoute,
  IfadeRaporuRoute: IfadeRaporuRoute,
  OlayRaporuRoute: OlayRaporuRoute,
  PaperworkGeneratorsRoute: PaperworkGeneratorsRoute,
  PenalCodeRoute: PenalCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
