/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AddCctvKayitTalepleriRouteImport } from './routes/add-cctv-kayit-talepleri'
import { Route as AddCeteSorusturmaDosyasiRouteImport } from './routes/add-cete-sorusturma-dosyasi'
import { Route as AddCeteTakipGuncellemeRouteImport } from './routes/add-cete-takip-guncelleme'
import { Route as AddK9DeploymentRaporuRouteImport } from './routes/add-k9-deployment-raporu'
import { Route as AddKategorikGucKullanimiRaporuRouteImport } from './routes/add-kategorik-guc-kullanimi-raporu'
import { Route as AddKategorikGucKullanimiTamamlayiciRaporuRouteImport } from './routes/add-kategorik-guc-kullanimi-tamamlayici-raporu'
import { Route as AddKazaSorusturmaRaporuRouteImport } from './routes/add-kaza-sorusturma-raporu'
import { Route as AddKazaSorusturmaRaporu2RouteImport } from './routes/add-kaza-sorusturma-raporu-2'
import { Route as AddKazaSorusturmaRaporu3RouteImport } from './routes/add-kaza-sorusturma-raporu-3'
import { Route as AddMetroGunlukAktiviteRaporuRouteImport } from './routes/add-metro-gunluk-aktivite-raporu'
import { Route as AddSorguRaporuRouteImport } from './routes/add-sorgu-raporu'
import { Route as AddTakipSorusturmaFormu1RouteImport } from './routes/add-takip-sorusturma-formu-1'
import { Route as AddTakipSorusturmaFormu2RouteImport } from './routes/add-takip-sorusturma-formu-2'
import { Route as AddTrafikOzelGorevlendirmeRaporuRouteImport } from './routes/add-trafik-ozel-gorevlendirme-raporu'
import { Route as AddWarrantHizmetleriRouteImport } from './routes/add-warrant-hizmetleri'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApbSablonuRouteImport } from './routes/apb-sablonu'
import { Route as AracElKoymaRaporuRouteImport } from './routes/arac-el-koyma-raporu'
import { Route as ArrestCalculatorRouteImport } from './routes/arrest-calculator'
import { Route as AyarlarRouteImport } from './routes/ayarlar'
import { Route as CalisanListesiRouteImport } from './routes/calisan-listesi'
import { Route as CaselawRouteImport } from './routes/caselaw'
import { Route as CentralTrafficDivisionRouteImport } from './routes/central-traffic-division'
import { Route as DetectivePortalRouteImport } from './routes/detective-portal'
import { Route as EPostaRouteImport } from './routes/e-posta'
import { Route as FieldInterviewKartiRouteImport } from './routes/field-interview-karti'
import { Route as GangEnforcementDetailRouteImport } from './routes/gang-enforcement-detail'
import { Route as GozaltiKayitFormuRouteImport } from './routes/gozalti-kayit-formu'
import { Route as IfadeRaporuRouteImport } from './routes/ifade-raporu'
import { Route as IhlalRaporuRouteImport } from './routes/ihlal-raporu'
import { Route as KartvizitRouteImport } from './routes/kartvizit'
import { Route as MetropolitanDivisionRouteImport } from './routes/metropolitan-division'
import { Route as OlayRaporuRouteImport } from './routes/olay-raporu'
import { Route as OnayBekliyorRouteImport } from './routes/onay-bekliyor'
import { Route as PaperworkGeneratorsRouteImport } from './routes/paperwork-generators'
import { Route as PenalCodeRouteImport } from './routes/penal-code'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as SupervisoryStaffRouteImport } from './routes/supervisory-staff'
import { Route as TutuklamaRaporuRouteImport } from './routes/tutuklama-raporu'
import { Route as AuthGirisRouteImport } from './routes/auth/giris'
import { Route as ProfilUserIdRouteImport } from './routes/profil_.$userId'
import { Route as AuthUcpCallbackRouteImport } from './routes/auth/ucp/callback'
import { Route as ApiPublicProfilePhotoSplatRouteImport } from './routes/api/public/profile-photo.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AddCctvKayitTalepleriRoute = AddCctvKayitTalepleriRouteImport.update({
  id: '/add-cctv-kayit-talepleri',
  path: '/add-cctv-kayit-talepleri',
  getParentRoute: () => rootRouteImport,
} as any)
const AddCeteSorusturmaDosyasiRoute =
  AddCeteSorusturmaDosyasiRouteImport.update({
    id: '/add-cete-sorusturma-dosyasi',
    path: '/add-cete-sorusturma-dosyasi',
    getParentRoute: () => rootRouteImport,
  } as any)
const AddCeteTakipGuncellemeRoute = AddCeteTakipGuncellemeRouteImport.update({
  id: '/add-cete-takip-guncelleme',
  path: '/add-cete-takip-guncelleme',
  getParentRoute: () => rootRouteImport,
} as any)
const AddK9DeploymentRaporuRoute = AddK9DeploymentRaporuRouteImport.update({
  id: '/add-k9-deployment-raporu',
  path: '/add-k9-deployment-raporu',
  getParentRoute: () => rootRouteImport,
} as any)
const AddKategorikGucKullanimiRaporuRoute =
  AddKategorikGucKullanimiRaporuRouteImport.update({
    id: '/add-kategorik-guc-kullanimi-raporu',
    path: '/add-kategorik-guc-kullanimi-raporu',
    getParentRoute: () => rootRouteImport,
  } as any)
const AddKategorikGucKullanimiTamamlayiciRaporuRoute =
  AddKategorikGucKullanimiTamamlayiciRaporuRouteImport.update({
    id: '/add-kategorik-guc-kullanimi-tamamlayici-raporu',
    path: '/add-kategorik-guc-kullanimi-tamamlayici-raporu',
    getParentRoute: () => rootRouteImport,
  } as any)
const AddKazaSorusturmaRaporuRoute = AddKazaSorusturmaRaporuRouteImport.update({
  id: '/add-kaza-sorusturma-raporu',
  path: '/add-kaza-sorusturma-raporu',
  getParentRoute: () => rootRouteImport,
} as any)
const AddKazaSorusturmaRaporu2Route =
  AddKazaSorusturmaRaporu2RouteImport.update({
    id: '/add-kaza-sorusturma-raporu-2',
    path: '/add-kaza-sorusturma-raporu-2',
    getParentRoute: () => rootRouteImport,
  } as any)
const AddKazaSorusturmaRaporu3Route =
  AddKazaSorusturmaRaporu3RouteImport.update({
    id: '/add-kaza-sorusturma-raporu-3',
    path: '/add-kaza-sorusturma-raporu-3',
    getParentRoute: () => rootRouteImport,
  } as any)
const AddMetroGunlukAktiviteRaporuRoute =
  AddMetroGunlukAktiviteRaporuRouteImport.update({
    id: '/add-metro-gunluk-aktivite-raporu',
    path: '/add-metro-gunluk-aktivite-raporu',
    getParentRoute: () => rootRouteImport,
  } as any)
const AddSorguRaporuRoute = AddSorguRaporuRouteImport.update({
  id: '/add-sorgu-raporu',
  path: '/add-sorgu-raporu',
  getParentRoute: () => rootRouteImport,
} as any)
const AddTakipSorusturmaFormu1Route =
  AddTakipSorusturmaFormu1RouteImport.update({
    id: '/add-takip-sorusturma-formu-1',
    path: '/add-takip-sorusturma-formu-1',
    getParentRoute: () => rootRouteImport,
  } as any)
const AddTakipSorusturmaFormu2Route =
  AddTakipSorusturmaFormu2RouteImport.update({
    id: '/add-takip-sorusturma-formu-2',
    path: '/add-takip-sorusturma-formu-2',
    getParentRoute: () => rootRouteImport,
  } as any)
const AddTrafikOzelGorevlendirmeRaporuRoute =
  AddTrafikOzelGorevlendirmeRaporuRouteImport.update({
    id: '/add-trafik-ozel-gorevlendirme-raporu',
    path: '/add-trafik-ozel-gorevlendirme-raporu',
    getParentRoute: () => rootRouteImport,
  } as any)
const AddWarrantHizmetleriRoute = AddWarrantHizmetleriRouteImport.update({
  id: '/add-warrant-hizmetleri',
  path: '/add-warrant-hizmetleri',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApbSablonuRoute = ApbSablonuRouteImport.update({
  id: '/apb-sablonu',
  path: '/apb-sablonu',
  getParentRoute: () => rootRouteImport,
} as any)
const AracElKoymaRaporuRoute = AracElKoymaRaporuRouteImport.update({
  id: '/arac-el-koyma-raporu',
  path: '/arac-el-koyma-raporu',
  getParentRoute: () => rootRouteImport,
} as any)
const ArrestCalculatorRoute = ArrestCalculatorRouteImport.update({
  id: '/arrest-calculator',
  path: '/arrest-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AyarlarRoute = AyarlarRouteImport.update({
  id: '/ayarlar',
  path: '/ayarlar',
  getParentRoute: () => rootRouteImport,
} as any)
const CalisanListesiRoute = CalisanListesiRouteImport.update({
  id: '/calisan-listesi',
  path: '/calisan-listesi',
  getParentRoute: () => rootRouteImport,
} as any)
const CaselawRoute = CaselawRouteImport.update({
  id: '/caselaw',
  path: '/caselaw',
  getParentRoute: () => rootRouteImport,
} as any)
const CentralTrafficDivisionRoute = CentralTrafficDivisionRouteImport.update({
  id: '/central-traffic-division',
  path: '/central-traffic-division',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectivePortalRoute = DetectivePortalRouteImport.update({
  id: '/detective-portal',
  path: '/detective-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const EPostaRoute = EPostaRouteImport.update({
  id: '/e-posta',
  path: '/e-posta',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldInterviewKartiRoute = FieldInterviewKartiRouteImport.update({
  id: '/field-interview-karti',
  path: '/field-interview-karti',
  getParentRoute: () => rootRouteImport,
} as any)
const GangEnforcementDetailRoute = GangEnforcementDetailRouteImport.update({
  id: '/gang-enforcement-detail',
  path: '/gang-enforcement-detail',
  getParentRoute: () => rootRouteImport,
} as any)
const GozaltiKayitFormuRoute = GozaltiKayitFormuRouteImport.update({
  id: '/gozalti-kayit-formu',
  path: '/gozalti-kayit-formu',
  getParentRoute: () => rootRouteImport,
} as any)
const IfadeRaporuRoute = IfadeRaporuRouteImport.update({
  id: '/ifade-raporu',
  path: '/ifade-raporu',
  getParentRoute: () => rootRouteImport,
} as any)
const IhlalRaporuRoute = IhlalRaporuRouteImport.update({
  id: '/ihlal-raporu',
  path: '/ihlal-raporu',
  getParentRoute: () => rootRouteImport,
} as any)
const KartvizitRoute = KartvizitRouteImport.update({
  id: '/kartvizit',
  path: '/kartvizit',
  getParentRoute: () => rootRouteImport,
} as any)
const MetropolitanDivisionRoute = MetropolitanDivisionRouteImport.update({
  id: '/metropolitan-division',
  path: '/metropolitan-division',
  getParentRoute: () => rootRouteImport,
} as any)
const OlayRaporuRoute = OlayRaporuRouteImport.update({
  id: '/olay-raporu',
  path: '/olay-raporu',
  getParentRoute: () => rootRouteImport,
} as any)
const OnayBekliyorRoute = OnayBekliyorRouteImport.update({
  id: '/onay-bekliyor',
  path: '/onay-bekliyor',
  getParentRoute: () => rootRouteImport,
} as any)
const PaperworkGeneratorsRoute = PaperworkGeneratorsRouteImport.update({
  id: '/paperwork-generators',
  path: '/paperwork-generators',
  getParentRoute: () => rootRouteImport,
} as any)
const PenalCodeRoute = PenalCodeRouteImport.update({
  id: '/penal-code',
  path: '/penal-code',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisoryStaffRoute = SupervisoryStaffRouteImport.update({
  id: '/supervisory-staff',
  path: '/supervisory-staff',
  getParentRoute: () => rootRouteImport,
} as any)
const TutuklamaRaporuRoute = TutuklamaRaporuRouteImport.update({
  id: '/tutuklama-raporu',
  path: '/tutuklama-raporu',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGirisRoute = AuthGirisRouteImport.update({
  id: '/auth/giris',
  path: '/auth/giris',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilUserIdRoute = ProfilUserIdRouteImport.update({
  id: '/profil_/$userId',
  path: '/profil/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUcpCallbackRoute = AuthUcpCallbackRouteImport.update({
  id: '/auth/ucp/callback',
  path: '/auth/ucp/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProfilePhotoSplatRoute =
  ApiPublicProfilePhotoSplatRouteImport.update({
    id: '/api/public/profile-photo/$',
    path: '/api/public/profile-photo/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-cctv-kayit-talepleri': typeof AddCctvKayitTalepleriRoute
  '/add-cete-sorusturma-dosyasi': typeof AddCeteSorusturmaDosyasiRoute
  '/add-cete-takip-guncelleme': typeof AddCeteTakipGuncellemeRoute
  '/add-k9-deployment-raporu': typeof AddK9DeploymentRaporuRoute
  '/add-kategorik-guc-kullanimi-raporu': typeof AddKategorikGucKullanimiRaporuRoute
  '/add-kategorik-guc-kullanimi-tamamlayici-raporu': typeof AddKategorikGucKullanimiTamamlayiciRaporuRoute
  '/add-kaza-sorusturma-raporu': typeof AddKazaSorusturmaRaporuRoute
  '/add-kaza-sorusturma-raporu-2': typeof AddKazaSorusturmaRaporu2Route
  '/add-kaza-sorusturma-raporu-3': typeof AddKazaSorusturmaRaporu3Route
  '/add-metro-gunluk-aktivite-raporu': typeof AddMetroGunlukAktiviteRaporuRoute
  '/add-sorgu-raporu': typeof AddSorguRaporuRoute
  '/add-takip-sorusturma-formu-1': typeof AddTakipSorusturmaFormu1Route
  '/add-takip-sorusturma-formu-2': typeof AddTakipSorusturmaFormu2Route
  '/add-trafik-ozel-gorevlendirme-raporu': typeof AddTrafikOzelGorevlendirmeRaporuRoute
  '/add-warrant-hizmetleri': typeof AddWarrantHizmetleriRoute
  '/admin': typeof AdminRoute
  '/apb-sablonu': typeof ApbSablonuRoute
  '/arac-el-koyma-raporu': typeof AracElKoymaRaporuRoute
  '/arrest-calculator': typeof ArrestCalculatorRoute
  '/ayarlar': typeof AyarlarRoute
  '/calisan-listesi': typeof CalisanListesiRoute
  '/caselaw': typeof CaselawRoute
  '/central-traffic-division': typeof CentralTrafficDivisionRoute
  '/detective-portal': typeof DetectivePortalRoute
  '/e-posta': typeof EPostaRoute
  '/field-interview-karti': typeof FieldInterviewKartiRoute
  '/gang-enforcement-detail': typeof GangEnforcementDetailRoute
  '/gozalti-kayit-formu': typeof GozaltiKayitFormuRoute
  '/ifade-raporu': typeof IfadeRaporuRoute
  '/ihlal-raporu': typeof IhlalRaporuRoute
  '/kartvizit': typeof KartvizitRoute
  '/metropolitan-division': typeof MetropolitanDivisionRoute
  '/olay-raporu': typeof OlayRaporuRoute
  '/onay-bekliyor': typeof OnayBekliyorRoute
  '/paperwork-generators': typeof PaperworkGeneratorsRoute
  '/penal-code': typeof PenalCodeRoute
  '/profil': typeof ProfilRoute
  '/supervisory-staff': typeof SupervisoryStaffRoute
  '/tutuklama-raporu': typeof TutuklamaRaporuRoute
  '/auth/giris': typeof AuthGirisRoute
  '/profil/$userId': typeof ProfilUserIdRoute
  '/auth/ucp/callback': typeof AuthUcpCallbackRoute
  '/api/public/profile-photo/$': typeof ApiPublicProfilePhotoSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-cctv-kayit-talepleri': typeof AddCctvKayitTalepleriRoute
  '/add-cete-sorusturma-dosyasi': typeof AddCeteSorusturmaDosyasiRoute
  '/add-cete-takip-guncelleme': typeof AddCeteTakipGuncellemeRoute
  '/add-k9-deployment-raporu': typeof AddK9DeploymentRaporuRoute
  '/add-kategorik-guc-kullanimi-raporu': typeof AddKategorikGucKullanimiRaporuRoute
  '/add-kategorik-guc-kullanimi-tamamlayici-raporu': typeof AddKategorikGucKullanimiTamamlayiciRaporuRoute
  '/add-kaza-sorusturma-raporu': typeof AddKazaSorusturmaRaporuRoute
  '/add-kaza-sorusturma-raporu-2': typeof AddKazaSorusturmaRaporu2Route
  '/add-kaza-sorusturma-raporu-3': typeof AddKazaSorusturmaRaporu3Route
  '/add-metro-gunluk-aktivite-raporu': typeof AddMetroGunlukAktiviteRaporuRoute
  '/add-sorgu-raporu': typeof AddSorguRaporuRoute
  '/add-takip-sorusturma-formu-1': typeof AddTakipSorusturmaFormu1Route
  '/add-takip-sorusturma-formu-2': typeof AddTakipSorusturmaFormu2Route
  '/add-trafik-ozel-gorevlendirme-raporu': typeof AddTrafikOzelGorevlendirmeRaporuRoute
  '/add-warrant-hizmetleri': typeof AddWarrantHizmetleriRoute
  '/admin': typeof AdminRoute
  '/apb-sablonu': typeof ApbSablonuRoute
  '/arac-el-koyma-raporu': typeof AracElKoymaRaporuRoute
  '/arrest-calculator': typeof ArrestCalculatorRoute
  '/ayarlar': typeof AyarlarRoute
  '/calisan-listesi': typeof CalisanListesiRoute
  '/caselaw': typeof CaselawRoute
  '/central-traffic-division': typeof CentralTrafficDivisionRoute
  '/detective-portal': typeof DetectivePortalRoute
  '/e-posta': typeof EPostaRoute
  '/field-interview-karti': typeof FieldInterviewKartiRoute
  '/gang-enforcement-detail': typeof GangEnforcementDetailRoute
  '/gozalti-kayit-formu': typeof GozaltiKayitFormuRoute
  '/ifade-raporu': typeof IfadeRaporuRoute
  '/ihlal-raporu': typeof IhlalRaporuRoute
  '/kartvizit': typeof KartvizitRoute
  '/metropolitan-division': typeof MetropolitanDivisionRoute
  '/olay-raporu': typeof OlayRaporuRoute
  '/onay-bekliyor': typeof OnayBekliyorRoute
  '/paperwork-generators': typeof PaperworkGeneratorsRoute
  '/penal-code': typeof PenalCodeRoute
  '/profil': typeof ProfilRoute
  '/supervisory-staff': typeof SupervisoryStaffRoute
  '/tutuklama-raporu': typeof TutuklamaRaporuRoute
  '/auth/giris': typeof AuthGirisRoute
  '/profil/$userId': typeof ProfilUserIdRoute
  '/auth/ucp/callback': typeof AuthUcpCallbackRoute
  '/api/public/profile-photo/$': typeof ApiPublicProfilePhotoSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-cctv-kayit-talepleri': typeof AddCctvKayitTalepleriRoute
  '/add-cete-sorusturma-dosyasi': typeof AddCeteSorusturmaDosyasiRoute
  '/add-cete-takip-guncelleme': typeof AddCeteTakipGuncellemeRoute
  '/add-k9-deployment-raporu': typeof AddK9DeploymentRaporuRoute
  '/add-kategorik-guc-kullanimi-raporu': typeof AddKategorikGucKullanimiRaporuRoute
  '/add-kategorik-guc-kullanimi-tamamlayici-raporu': typeof AddKategorikGucKullanimiTamamlayiciRaporuRoute
  '/add-kaza-sorusturma-raporu': typeof AddKazaSorusturmaRaporuRoute
  '/add-kaza-sorusturma-raporu-2': typeof AddKazaSorusturmaRaporu2Route
  '/add-kaza-sorusturma-raporu-3': typeof AddKazaSorusturmaRaporu3Route
  '/add-metro-gunluk-aktivite-raporu': typeof AddMetroGunlukAktiviteRaporuRoute
  '/add-sorgu-raporu': typeof AddSorguRaporuRoute
  '/add-takip-sorusturma-formu-1': typeof AddTakipSorusturmaFormu1Route
  '/add-takip-sorusturma-formu-2': typeof AddTakipSorusturmaFormu2Route
  '/add-trafik-ozel-gorevlendirme-raporu': typeof AddTrafikOzelGorevlendirmeRaporuRoute
  '/add-warrant-hizmetleri': typeof AddWarrantHizmetleriRoute
  '/admin': typeof AdminRoute
  '/apb-sablonu': typeof ApbSablonuRoute
  '/arac-el-koyma-raporu': typeof AracElKoymaRaporuRoute
  '/arrest-calculator': typeof ArrestCalculatorRoute
  '/ayarlar': typeof AyarlarRoute
  '/calisan-listesi': typeof CalisanListesiRoute
  '/caselaw': typeof CaselawRoute
  '/central-traffic-division': typeof CentralTrafficDivisionRoute
  '/detective-portal': typeof DetectivePortalRoute
  '/e-posta': typeof EPostaRoute
  '/field-interview-karti': typeof FieldInterviewKartiRoute
  '/gang-enforcement-detail': typeof GangEnforcementDetailRoute
  '/gozalti-kayit-formu': typeof GozaltiKayitFormuRoute
  '/ifade-raporu': typeof IfadeRaporuRoute
  '/ihlal-raporu': typeof IhlalRaporuRoute
  '/kartvizit': typeof KartvizitRoute
  '/metropolitan-division': typeof MetropolitanDivisionRoute
  '/olay-raporu': typeof OlayRaporuRoute
  '/onay-bekliyor': typeof OnayBekliyorRoute
  '/paperwork-generators': typeof PaperworkGeneratorsRoute
  '/penal-code': typeof PenalCodeRoute
  '/profil': typeof ProfilRoute
  '/supervisory-staff': typeof SupervisoryStaffRoute
  '/tutuklama-raporu': typeof TutuklamaRaporuRoute
  '/auth/giris': typeof AuthGirisRoute
  '/profil_/$userId': typeof ProfilUserIdRoute
  '/auth/ucp/callback': typeof AuthUcpCallbackRoute
  '/api/public/profile-photo/$': typeof ApiPublicProfilePhotoSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-cctv-kayit-talepleri'
    | '/add-cete-sorusturma-dosyasi'
    | '/add-cete-takip-guncelleme'
    | '/add-k9-deployment-raporu'
    | '/add-kategorik-guc-kullanimi-raporu'
    | '/add-kategorik-guc-kullanimi-tamamlayici-raporu'
    | '/add-kaza-sorusturma-raporu'
    | '/add-kaza-sorusturma-raporu-2'
    | '/add-kaza-sorusturma-raporu-3'
    | '/add-metro-gunluk-aktivite-raporu'
    | '/add-sorgu-raporu'
    | '/add-takip-sorusturma-formu-1'
    | '/add-takip-sorusturma-formu-2'
    | '/add-trafik-ozel-gorevlendirme-raporu'
    | '/add-warrant-hizmetleri'
    | '/admin'
    | '/apb-sablonu'
    | '/arac-el-koyma-raporu'
    | '/arrest-calculator'
    | '/ayarlar'
    | '/calisan-listesi'
    | '/caselaw'
    | '/central-traffic-division'
    | '/detective-portal'
    | '/e-posta'
    | '/field-interview-karti'
    | '/gang-enforcement-detail'
    | '/gozalti-kayit-formu'
    | '/ifade-raporu'
    | '/ihlal-raporu'
    | '/kartvizit'
    | '/metropolitan-division'
    | '/olay-raporu'
    | '/onay-bekliyor'
    | '/paperwork-generators'
    | '/penal-code'
    | '/profil'
    | '/supervisory-staff'
    | '/tutuklama-raporu'
    | '/auth/giris'
    | '/profil/$userId'
    | '/auth/ucp/callback'
    | '/api/public/profile-photo/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-cctv-kayit-talepleri'
    | '/add-cete-sorusturma-dosyasi'
    | '/add-cete-takip-guncelleme'
    | '/add-k9-deployment-raporu'
    | '/add-kategorik-guc-kullanimi-raporu'
    | '/add-kategorik-guc-kullanimi-tamamlayici-raporu'
    | '/add-kaza-sorusturma-raporu'
    | '/add-kaza-sorusturma-raporu-2'
    | '/add-kaza-sorusturma-raporu-3'
    | '/add-metro-gunluk-aktivite-raporu'
    | '/add-sorgu-raporu'
    | '/add-takip-sorusturma-formu-1'
    | '/add-takip-sorusturma-formu-2'
    | '/add-trafik-ozel-gorevlendirme-raporu'
    | '/add-warrant-hizmetleri'
    | '/admin'
    | '/apb-sablonu'
    | '/arac-el-koyma-raporu'
    | '/arrest-calculator'
    | '/ayarlar'
    | '/calisan-listesi'
    | '/caselaw'
    | '/central-traffic-division'
    | '/detective-portal'
    | '/e-posta'
    | '/field-interview-karti'
    | '/gang-enforcement-detail'
    | '/gozalti-kayit-formu'
    | '/ifade-raporu'
    | '/ihlal-raporu'
    | '/kartvizit'
    | '/metropolitan-division'
    | '/olay-raporu'
    | '/onay-bekliyor'
    | '/paperwork-generators'
    | '/penal-code'
    | '/profil'
    | '/supervisory-staff'
    | '/tutuklama-raporu'
    | '/auth/giris'
    | '/profil/$userId'
    | '/auth/ucp/callback'
    | '/api/public/profile-photo/$'
  id:
    | '__root__'
    | '/'
    | '/add-cctv-kayit-talepleri'
    | '/add-cete-sorusturma-dosyasi'
    | '/add-cete-takip-guncelleme'
    | '/add-k9-deployment-raporu'
    | '/add-kategorik-guc-kullanimi-raporu'
    | '/add-kategorik-guc-kullanimi-tamamlayici-raporu'
    | '/add-kaza-sorusturma-raporu'
    | '/add-kaza-sorusturma-raporu-2'
    | '/add-kaza-sorusturma-raporu-3'
    | '/add-metro-gunluk-aktivite-raporu'
    | '/add-sorgu-raporu'
    | '/add-takip-sorusturma-formu-1'
    | '/add-takip-sorusturma-formu-2'
    | '/add-trafik-ozel-gorevlendirme-raporu'
    | '/add-warrant-hizmetleri'
    | '/admin'
    | '/apb-sablonu'
    | '/arac-el-koyma-raporu'
    | '/arrest-calculator'
    | '/ayarlar'
    | '/calisan-listesi'
    | '/caselaw'
    | '/central-traffic-division'
    | '/detective-portal'
    | '/e-posta'
    | '/field-interview-karti'
    | '/gang-enforcement-detail'
    | '/gozalti-kayit-formu'
    | '/ifade-raporu'
    | '/ihlal-raporu'
    | '/kartvizit'
    | '/metropolitan-division'
    | '/olay-raporu'
    | '/onay-bekliyor'
    | '/paperwork-generators'
    | '/penal-code'
    | '/profil'
    | '/supervisory-staff'
    | '/tutuklama-raporu'
    | '/auth/giris'
    | '/profil_/$userId'
    | '/auth/ucp/callback'
    | '/api/public/profile-photo/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddCctvKayitTalepleriRoute: typeof AddCctvKayitTalepleriRoute
  AddCeteSorusturmaDosyasiRoute: typeof AddCeteSorusturmaDosyasiRoute
  AddCeteTakipGuncellemeRoute: typeof AddCeteTakipGuncellemeRoute
  AddK9DeploymentRaporuRoute: typeof AddK9DeploymentRaporuRoute
  AddKategorikGucKullanimiRaporuRoute: typeof AddKategorikGucKullanimiRaporuRoute
  AddKategorikGucKullanimiTamamlayiciRaporuRoute: typeof AddKategorikGucKullanimiTamamlayiciRaporuRoute
  AddKazaSorusturmaRaporuRoute: typeof AddKazaSorusturmaRaporuRoute
  AddKazaSorusturmaRaporu2Route: typeof AddKazaSorusturmaRaporu2Route
  AddKazaSorusturmaRaporu3Route: typeof AddKazaSorusturmaRaporu3Route
  AddMetroGunlukAktiviteRaporuRoute: typeof AddMetroGunlukAktiviteRaporuRoute
  AddSorguRaporuRoute: typeof AddSorguRaporuRoute
  AddTakipSorusturmaFormu1Route: typeof AddTakipSorusturmaFormu1Route
  AddTakipSorusturmaFormu2Route: typeof AddTakipSorusturmaFormu2Route
  AddTrafikOzelGorevlendirmeRaporuRoute: typeof AddTrafikOzelGorevlendirmeRaporuRoute
  AddWarrantHizmetleriRoute: typeof AddWarrantHizmetleriRoute
  AdminRoute: typeof AdminRoute
  ApbSablonuRoute: typeof ApbSablonuRoute
  AracElKoymaRaporuRoute: typeof AracElKoymaRaporuRoute
  ArrestCalculatorRoute: typeof ArrestCalculatorRoute
  AyarlarRoute: typeof AyarlarRoute
  CalisanListesiRoute: typeof CalisanListesiRoute
  CaselawRoute: typeof CaselawRoute
  CentralTrafficDivisionRoute: typeof CentralTrafficDivisionRoute
  DetectivePortalRoute: typeof DetectivePortalRoute
  EPostaRoute: typeof EPostaRoute
  FieldInterviewKartiRoute: typeof FieldInterviewKartiRoute
  GangEnforcementDetailRoute: typeof GangEnforcementDetailRoute
  GozaltiKayitFormuRoute: typeof GozaltiKayitFormuRoute
  IfadeRaporuRoute: typeof IfadeRaporuRoute
  IhlalRaporuRoute: typeof IhlalRaporuRoute
  KartvizitRoute: typeof KartvizitRoute
  MetropolitanDivisionRoute: typeof MetropolitanDivisionRoute
  OlayRaporuRoute: typeof OlayRaporuRoute
  OnayBekliyorRoute: typeof OnayBekliyorRoute
  PaperworkGeneratorsRoute: typeof PaperworkGeneratorsRoute
  PenalCodeRoute: typeof PenalCodeRoute
  ProfilRoute: typeof ProfilRoute
  SupervisoryStaffRoute: typeof SupervisoryStaffRoute
  TutuklamaRaporuRoute: typeof TutuklamaRaporuRoute
  AuthGirisRoute: typeof AuthGirisRoute
  ProfilUserIdRoute: typeof ProfilUserIdRoute
  AuthUcpCallbackRoute: typeof AuthUcpCallbackRoute
  ApiPublicProfilePhotoSplatRoute: typeof ApiPublicProfilePhotoSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-cctv-kayit-talepleri': {
      id: '/add-cctv-kayit-talepleri'
      path: '/add-cctv-kayit-talepleri'
      fullPath: '/add-cctv-kayit-talepleri'
      preLoaderRoute: typeof AddCctvKayitTalepleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-cete-sorusturma-dosyasi': {
      id: '/add-cete-sorusturma-dosyasi'
      path: '/add-cete-sorusturma-dosyasi'
      fullPath: '/add-cete-sorusturma-dosyasi'
      preLoaderRoute: typeof AddCeteSorusturmaDosyasiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-cete-takip-guncelleme': {
      id: '/add-cete-takip-guncelleme'
      path: '/add-cete-takip-guncelleme'
      fullPath: '/add-cete-takip-guncelleme'
      preLoaderRoute: typeof AddCeteTakipGuncellemeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-k9-deployment-raporu': {
      id: '/add-k9-deployment-raporu'
      path: '/add-k9-deployment-raporu'
      fullPath: '/add-k9-deployment-raporu'
      preLoaderRoute: typeof AddK9DeploymentRaporuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-kategorik-guc-kullanimi-raporu': {
      id: '/add-kategorik-guc-kullanimi-raporu'
      path: '/add-kategorik-guc-kullanimi-raporu'
      fullPath: '/add-kategorik-guc-kullanimi-raporu'
      preLoaderRoute: typeof AddKategorikGucKullanimiRaporuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-kategorik-guc-kullanimi-tamamlayici-raporu': {
      id: '/add-kategorik-guc-kullanimi-tamamlayici-raporu'
      path: '/add-kategorik-guc-kullanimi-tamamlayici-raporu'
      fullPath: '/add-kategorik-guc-kullanimi-tamamlayici-raporu'
      preLoaderRoute: typeof AddKategorikGucKullanimiTamamlayiciRaporuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-kaza-sorusturma-raporu': {
      id: '/add-kaza-sorusturma-raporu'
      path: '/add-kaza-sorusturma-raporu'
      fullPath: '/add-kaza-sorusturma-raporu'
      preLoaderRoute: typeof AddKazaSorusturmaRaporuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-kaza-sorusturma-raporu-2': {
      id: '/add-kaza-sorusturma-raporu-2'
      path: '/add-kaza-sorusturma-raporu-2'
      fullPath: '/add-kaza-sorusturma-raporu-2'
      preLoaderRoute: typeof AddKazaSorusturmaRaporu2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-kaza-sorusturma-raporu-3': {
      id: '/add-kaza-sorusturma-raporu-3'
      path: '/add-kaza-sorusturma-raporu-3'
      fullPath: '/add-kaza-sorusturma-raporu-3'
      preLoaderRoute: typeof AddKazaSorusturmaRaporu3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-metro-gunluk-aktivite-raporu': {
      id: '/add-metro-gunluk-aktivite-raporu'
      path: '/add-metro-gunluk-aktivite-raporu'
      fullPath: '/add-metro-gunluk-aktivite-raporu'
      preLoaderRoute: typeof AddMetroGunlukAktiviteRaporuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-sorgu-raporu': {
      id: '/add-sorgu-raporu'
      path: '/add-sorgu-raporu'
      fullPath: '/add-sorgu-raporu'
      preLoaderRoute: typeof AddSorguRaporuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-takip-sorusturma-formu-1': {
      id: '/add-takip-sorusturma-formu-1'
      path: '/add-takip-sorusturma-formu-1'
      fullPath: '/add-takip-sorusturma-formu-1'
      preLoaderRoute: typeof AddTakipSorusturmaFormu1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-takip-sorusturma-formu-2': {
      id: '/add-takip-sorusturma-formu-2'
      path: '/add-takip-sorusturma-formu-2'
      fullPath: '/add-takip-sorusturma-formu-2'
      preLoaderRoute: typeof AddTakipSorusturmaFormu2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-trafik-ozel-gorevlendirme-raporu': {
      id: '/add-trafik-ozel-gorevlendirme-raporu'
      path: '/add-trafik-ozel-gorevlendirme-raporu'
      fullPath: '/add-trafik-ozel-gorevlendirme-raporu'
      preLoaderRoute: typeof AddTrafikOzelGorevlendirmeRaporuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-warrant-hizmetleri': {
      id: '/add-warrant-hizmetleri'
      path: '/add-warrant-hizmetleri'
      fullPath: '/add-warrant-hizmetleri'
      preLoaderRoute: typeof AddWarrantHizmetleriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apb-sablonu': {
      id: '/apb-sablonu'
      path: '/apb-sablonu'
      fullPath: '/apb-sablonu'
      preLoaderRoute: typeof ApbSablonuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arac-el-koyma-raporu': {
      id: '/arac-el-koyma-raporu'
      path: '/arac-el-koyma-raporu'
      fullPath: '/arac-el-koyma-raporu'
      preLoaderRoute: typeof AracElKoymaRaporuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arrest-calculator': {
      id: '/arrest-calculator'
      path: '/arrest-calculator'
      fullPath: '/arrest-calculator'
      preLoaderRoute: typeof ArrestCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayarlar': {
      id: '/ayarlar'
      path: '/ayarlar'
      fullPath: '/ayarlar'
      preLoaderRoute: typeof AyarlarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calisan-listesi': {
      id: '/calisan-listesi'
      path: '/calisan-listesi'
      fullPath: '/calisan-listesi'
      preLoaderRoute: typeof CalisanListesiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caselaw': {
      id: '/caselaw'
      path: '/caselaw'
      fullPath: '/caselaw'
      preLoaderRoute: typeof CaselawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/central-traffic-division': {
      id: '/central-traffic-division'
      path: '/central-traffic-division'
      fullPath: '/central-traffic-division'
      preLoaderRoute: typeof CentralTrafficDivisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detective-portal': {
      id: '/detective-portal'
      path: '/detective-portal'
      fullPath: '/detective-portal'
      preLoaderRoute: typeof DetectivePortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/e-posta': {
      id: '/e-posta'
      path: '/e-posta'
      fullPath: '/e-posta'
      preLoaderRoute: typeof EPostaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-interview-karti': {
      id: '/field-interview-karti'
      path: '/field-interview-karti'
      fullPath: '/field-interview-karti'
      preLoaderRoute: typeof FieldInterviewKartiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gang-enforcement-detail': {
      id: '/gang-enforcement-detail'
      path: '/gang-enforcement-detail'
      fullPath: '/gang-enforcement-detail'
      preLoaderRoute: typeof GangEnforcementDetailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gozalti-kayit-formu': {
      id: '/gozalti-kayit-formu'
      path: '/gozalti-kayit-formu'
      fullPath: '/gozalti-kayit-formu'
      preLoaderRoute: typeof GozaltiKayitFormuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ifade-raporu': {
      id: '/ifade-raporu'
      path: '/ifade-raporu'
      fullPath: '/ifade-raporu'
      preLoaderRoute: typeof IfadeRaporuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ihlal-raporu': {
      id: '/ihlal-raporu'
      path: '/ihlal-raporu'
      fullPath: '/ihlal-raporu'
      preLoaderRoute: typeof IhlalRaporuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kartvizit': {
      id: '/kartvizit'
      path: '/kartvizit'
      fullPath: '/kartvizit'
      preLoaderRoute: typeof KartvizitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metropolitan-division': {
      id: '/metropolitan-division'
      path: '/metropolitan-division'
      fullPath: '/metropolitan-division'
      preLoaderRoute: typeof MetropolitanDivisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/olay-raporu': {
      id: '/olay-raporu'
      path: '/olay-raporu'
      fullPath: '/olay-raporu'
      preLoaderRoute: typeof OlayRaporuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onay-bekliyor': {
      id: '/onay-bekliyor'
      path: '/onay-bekliyor'
      fullPath: '/onay-bekliyor'
      preLoaderRoute: typeof OnayBekliyorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paperwork-generators': {
      id: '/paperwork-generators'
      path: '/paperwork-generators'
      fullPath: '/paperwork-generators'
      preLoaderRoute: typeof PaperworkGeneratorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/penal-code': {
      id: '/penal-code'
      path: '/penal-code'
      fullPath: '/penal-code'
      preLoaderRoute: typeof PenalCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisory-staff': {
      id: '/supervisory-staff'
      path: '/supervisory-staff'
      fullPath: '/supervisory-staff'
      preLoaderRoute: typeof SupervisoryStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutuklama-raporu': {
      id: '/tutuklama-raporu'
      path: '/tutuklama-raporu'
      fullPath: '/tutuklama-raporu'
      preLoaderRoute: typeof TutuklamaRaporuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/giris': {
      id: '/auth/giris'
      path: '/auth/giris'
      fullPath: '/auth/giris'
      preLoaderRoute: typeof AuthGirisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profil_/$userId': {
      id: '/profil_/$userId'
      path: '/profil/$userId'
      fullPath: '/profil/$userId'
      preLoaderRoute: typeof ProfilUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/ucp/callback': {
      id: '/auth/ucp/callback'
      path: '/auth/ucp/callback'
      fullPath: '/auth/ucp/callback'
      preLoaderRoute: typeof AuthUcpCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/profile-photo/$': {
      id: '/api/public/profile-photo/$'
      path: '/api/public/profile-photo/$'
      fullPath: '/api/public/profile-photo/$'
      preLoaderRoute: typeof ApiPublicProfilePhotoSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddCctvKayitTalepleriRoute: AddCctvKayitTalepleriRoute,
  AddCeteSorusturmaDosyasiRoute: AddCeteSorusturmaDosyasiRoute,
  AddCeteTakipGuncellemeRoute: AddCeteTakipGuncellemeRoute,
  AddK9DeploymentRaporuRoute: AddK9DeploymentRaporuRoute,
  AddKategorikGucKullanimiRaporuRoute: AddKategorikGucKullanimiRaporuRoute,
  AddKategorikGucKullanimiTamamlayiciRaporuRoute:
    AddKategorikGucKullanimiTamamlayiciRaporuRoute,
  AddKazaSorusturmaRaporuRoute: AddKazaSorusturmaRaporuRoute,
  AddKazaSorusturmaRaporu2Route: AddKazaSorusturmaRaporu2Route,
  AddKazaSorusturmaRaporu3Route: AddKazaSorusturmaRaporu3Route,
  AddMetroGunlukAktiviteRaporuRoute: AddMetroGunlukAktiviteRaporuRoute,
  AddSorguRaporuRoute: AddSorguRaporuRoute,
  AddTakipSorusturmaFormu1Route: AddTakipSorusturmaFormu1Route,
  AddTakipSorusturmaFormu2Route: AddTakipSorusturmaFormu2Route,
  AddTrafikOzelGorevlendirmeRaporuRoute: AddTrafikOzelGorevlendirmeRaporuRoute,
  AddWarrantHizmetleriRoute: AddWarrantHizmetleriRoute,
  AdminRoute: AdminRoute,
  ApbSablonuRoute: ApbSablonuRoute,
  AracElKoymaRaporuRoute: AracElKoymaRaporuRoute,
  ArrestCalculatorRoute: ArrestCalculatorRoute,
  AyarlarRoute: AyarlarRoute,
  CalisanListesiRoute: CalisanListesiRoute,
  CaselawRoute: CaselawRoute,
  CentralTrafficDivisionRoute: CentralTrafficDivisionRoute,
  DetectivePortalRoute: DetectivePortalRoute,
  EPostaRoute: EPostaRoute,
  FieldInterviewKartiRoute: FieldInterviewKartiRoute,
  GangEnforcementDetailRoute: GangEnforcementDetailRoute,
  GozaltiKayitFormuRoute: GozaltiKayitFormuRoute,
  IfadeRaporuRoute: IfadeRaporuRoute,
  IhlalRaporuRoute: IhlalRaporuRoute,
  KartvizitRoute: KartvizitRoute,
  MetropolitanDivisionRoute: MetropolitanDivisionRoute,
  OlayRaporuRoute: OlayRaporuRoute,
  OnayBekliyorRoute: OnayBekliyorRoute,
  PaperworkGeneratorsRoute: PaperworkGeneratorsRoute,
  PenalCodeRoute: PenalCodeRoute,
  ProfilRoute: ProfilRoute,
  SupervisoryStaffRoute: SupervisoryStaffRoute,
  TutuklamaRaporuRoute: TutuklamaRaporuRoute,
  AuthGirisRoute: AuthGirisRoute,
  ProfilUserIdRoute: ProfilUserIdRoute,
  AuthUcpCallbackRoute: AuthUcpCallbackRoute,
  ApiPublicProfilePhotoSplatRoute: ApiPublicProfilePhotoSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
